### ISSUE TITLE
Amazon Polly

### ISSUE THREAD

**Issue by jjanderson** [sdesalve/hassio-addons#36]
Hey,

Thanks for this great addon!

Herewith the information from the addon logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.5.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (amd64 / qemux86-64)
 Home Assistant Core: 2021.3.0
 Home Assistant Supervisor: 2021.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
[Info] Listening for messages via stdin service call...
```

I am however having some trouble using Amazon Polly as the TTS platform. I have read the docs, but al lthat is mentioned is this:

Option platform_tts (Optional)
Specify Text-to-speech platform to use. Default value if this option is not specified is google_translate. For a list of available TTS integration please see Hassio integrations

Here is my config:

```
sip_parameters:
  caller_id_uri: 'sip:100@iotci.3cx.co.uk'
  realm: '*'
  platform_tts: amazon_polly
  username: 'xxxxxxxxxxx'
  password: xxxxxxxxx
```

However, when I call the service, I get this error:

Logger: aiohttp.server
Source: components/tts/__init__.py:324
First occurred: 12:28:01 (1 occurrences)
Last logged: 12:28:01

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 606, in post
    path = await self.tts.async_get_url_path(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 324, in async_get_url_path
    provider = self.providers[engine]
KeyError: 'google_translate'
```

Could youi provide a few more details or even an example on how to integrate various other TTS providers into the addon?

Many thanks again for this great addon!

**Comment by sdesalve** [comment]
https://github.com/sdesalve/hassio-addons/tree/master/dss_voip#option-platform_tts-optional

platform_tts is not a children of sip_parameters:

```
sip_parameters:
  caller_id_uri: 'sip:100@iotci.3cx.co.uk'
  realm: '*'
  username: 'xxxxxxxxxxx'
  password: xxxxxxxxx
platform_tts: amazon_polly
```
